services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      # Bind mount to persist data on local machine
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped